#!/bin/bash

echo "🎉 Good news! Your server is already running!"
echo ""
echo "✅ Server is active on port 3000"
echo ""
echo "🚀 TO TEST THE CHATBOT:"
echo ""
echo "1. Open your browser and go to:"
echo "   👉 http://localhost:3000"
echo ""
echo "2. Look for the PURPLE CHAT BUTTON in the bottom-right corner"
echo ""
echo "3. Click the button to open the chat"
echo ""
echo "4. Try these test messages:"
echo "   • 'What items are available?' (tests agentic scraping)"
echo "   • 'What are your business hours?'"
echo "   • 'How do I schedule an appointment?'"
echo ""
echo "💡 TIP: Open browser developer console (F12) to see API calls"
echo ""
echo "To stop the server, find the terminal where it's running and press Ctrl+C"
echo ""
